# Generated by Django 5.1.4 on 2026-08-06 18:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "PENDIENTE"),
                            ("COMPLETADA", "COMPLETADA"),
                            ("POSPUESTA", "POSPUESTA"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(default="system", max_length=150)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="tasks_status_031d4c_idx"),
                    models.Index(fields=["due_date"], name="tasks_due_dat_0359a9_idx"),
                    models.Index(
                        fields=["is_deleted"], name="tasks_is_dele_8a1818_idx"
                    ),
                ],
            },
        ),
    ]
